version: "3.8"
services:
  flume:
    image: flumetest:latest
    container_name: flume
    restart: unless-stopped
    volumes:
      - ./flume.log:/opt/flume/flume.log
    ports:
      - "44444:44444"
    environment:
      - FLUME_AGENT_NAME:agent
      - FLUME_CONF_FILE:/var/tmp/flume-timeinterxeptor.conf

